site:
  title: "MOEHANS BLOG"
  subtitle: "Share AI, Serverless, and Cloud Native"
  url: "https://moehans.com"
  lang: "zh_CN"
  author: "MOEHANS"
  email: "muyuzier@gmail.com"
  favicon: "/images/moehans-favicon.webp"
  og_image: "/images/og.webp"

profile:
  avatar: "/images/moehans-avatar.webp"
  name: "MOEHANS"
  bio: "优秀的公司赚取利润，伟大的公司赢得人心！"
  links:
    - name: "GitHub"
      url: "https://github.com/muyuzier-afk"
    - name: "Gitee"
      url: "https://gitee.com/muyuzier-afk"
    - name: "Email"
      url: "mailto:muyuzier@gmail.com"

nav:
  - Home: "/"
  - Archive: "/archive/"
  - Search: "/search/"
  - Series: "/seri/"
  - Links: "/links/"

features:
  comments: false
  search: true
  rss_feed: true
  related_posts: true
  series: true

seo:
  keywords: "astro, theme, blog, lonetrail, arknights"

copyright:
  site_name: "MOEHANS BLOG"
  license: "CC BY-NC-SA 4.0"
  license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

trusted_domains:
  - "www.moehans.com"
  - "moehans.com"
  - "github.com"
  - "gitee.com"
